//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocUpload
    {
        public int ID { get; set; }
        public string DocName { get; set; }
        public string DocImagePath { get; set; }
        public Nullable<int> User_FK { get; set; }
        public string ReferenceNum { get; set; }
        public string Loan_Fk { get; set; }
        public string Cols1 { get; set; }
        public string Cols2 { get; set; }
    }
}
