//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerTransact
    {
        public int ID { get; set; }
        public string ReferenceNum { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<double> Debit { get; set; }
        public string ValueDate { get; set; }
        public string ValueTime { get; set; }
        public Nullable<double> cols { get; set; }
        public Nullable<double> colss { get; set; }
        public string colsss { get; set; }
        public string colssss { get; set; }
    }
}
