//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyRepayment
    {
        public int ID { get; set; }
        public string ResponseCode { get; set; }
        public string RespDescription { get; set; }
        public Nullable<double> Amount { get; set; }
        public string RequestID { get; set; }
        public string MandateID { get; set; }
        public string TransactionRef { get; set; }
        public string RRR { get; set; }
        public string RefNumber { get; set; }
        public string FundingBankCode { get; set; }
        public string FundingAccount { get; set; }
        public Nullable<System.DateTime> TransactDate { get; set; }
        public string RespExtra { get; set; }
        public string RespExtra1 { get; set; }
        public string RespExtra2 { get; set; }
        public string Response { get; set; }
    }
}
