//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerT.DataManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UvlotEntities : DbContext
    {
        public UvlotEntities()
            : base("name=UvlotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccomodationType> AccomodationTypes { get; set; }
        public virtual DbSet<ApplicationStatu> ApplicationStatus { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Bankold> Bankolds { get; set; }
        public virtual DbSet<BanksManager> BanksManagers { get; set; }
        public virtual DbSet<DocUpload> DocUploads { get; set; }
        public virtual DbSet<EmployerLoanDetail> EmployerLoanDetails { get; set; }
        public virtual DbSet<EmploymentStatu> EmploymentStatus { get; set; }
        public virtual DbSet<Guarantor> Guarantors { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<InstitutionType> InstitutionTypes { get; set; }
        public virtual DbSet<LedgerTransact> LedgerTransacts { get; set; }
        public virtual DbSet<LGA> LGAs { get; set; }
        public virtual DbSet<LoanApplication> LoanApplications { get; set; }
        public virtual DbSet<LoanApproval> LoanApprovals { get; set; }
        public virtual DbSet<LoanInterestRate> LoanInterestRates { get; set; }
        public virtual DbSet<LoanLedger> LoanLedgers { get; set; }
        public virtual DbSet<LoanProduct> LoanProducts { get; set; }
        public virtual DbSet<LoansLedger> LoansLedgers { get; set; }
        public virtual DbSet<LoanTenure> LoanTenures { get; set; }
        public virtual DbSet<LoanType> LoanTypes { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<MeansOfIdentification> MeansOfIdentifications { get; set; }
        public virtual DbSet<MonthlyRepayment> MonthlyRepayments { get; set; }
        public virtual DbSet<NigerianState> NigerianStates { get; set; }
        public virtual DbSet<NYSCApplicationStatu> NYSCApplicationStatus { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PageAuthentication> PageAuthentications { get; set; }
        public virtual DbSet<pageHeader> pageHeaders { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<PatnerTransactLog> PatnerTransactLogs { get; set; }
        public virtual DbSet<PaymentFlag> PaymentFlags { get; set; }
        public virtual DbSet<RepaymentMethod> RepaymentMethods { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Signature> Signatures { get; set; }
        public virtual DbSet<StudentLoanDetail> StudentLoanDetails { get; set; }
        public virtual DbSet<StudentRecord> StudentRecords { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<NewLedgerTransact> NewLedgerTransacts { get; set; }
        public virtual DbSet<NewLoanLedger> NewLoanLedgers { get; set; }
    
        public virtual ObjectResult<BorroweredLoan_Result> BorroweredLoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BorroweredLoan_Result>("BorroweredLoan");
        }
    
        public virtual ObjectResult<DisbursedLoans_Result> DisbursedLoans()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DisbursedLoans_Result>("DisbursedLoans");
        }
    
        public virtual ObjectResult<GetReferrals_Result> GetReferrals(Nullable<int> roleID)
        {
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReferrals_Result>("GetReferrals", roleIDParameter);
        }
    
        public virtual ObjectResult<Invoice_Result> Invoice(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Invoice_Result>("Invoice", dateParameter);
        }
    
        public virtual ObjectResult<LoanDueForDebit_Result> LoanDueForDebit(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoanDueForDebit_Result>("LoanDueForDebit", dateParameter);
        }
    
        public virtual int LoanPerformance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoanPerformance");
        }
    
        public virtual ObjectResult<LoanRepayment_Result> LoanRepayment(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoanRepayment_Result>("LoanRepayment", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<LoanTransactionbyDate_Result> LoanTransactionbyDate(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoanTransactionbyDate_Result>("LoanTransactionbyDate", startDateParameter, endDateParameter);
        }
    
        public virtual int OutstandingLoan(Nullable<System.DateTime> endDate)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OutstandingLoan", endDateParameter);
        }
    
        public virtual ObjectResult<PayrollApplicationRelated_Result> PayrollApplicationRelated(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollApplicationRelated_Result>("PayrollApplicationRelated", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<PayrollBorroweredLoans_Result> PayrollBorroweredLoans()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollBorroweredLoans_Result>("PayrollBorroweredLoans");
        }
    
        public virtual ObjectResult<PayrollDisbursedLoans_Result> PayrollDisbursedLoans()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollDisbursedLoans_Result>("PayrollDisbursedLoans");
        }
    
        public virtual ObjectResult<PayrollLoanDueForDebit_Result> PayrollLoanDueForDebit(Nullable<System.DateTime> date)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollLoanDueForDebit_Result>("PayrollLoanDueForDebit", dateParameter);
        }
    
        public virtual ObjectResult<PayrollLoanPerformance_Result> PayrollLoanPerformance(Nullable<System.DateTime> endDate)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollLoanPerformance_Result>("PayrollLoanPerformance", endDateParameter);
        }
    
        public virtual ObjectResult<PayrollOutstandingLoan_Result> PayrollOutstandingLoan(Nullable<System.DateTime> endDate)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollOutstandingLoan_Result>("PayrollOutstandingLoan", endDateParameter);
        }
    
        public virtual ObjectResult<PayrollregistrationRelated_Result> PayrollregistrationRelated(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollregistrationRelated_Result>("PayrollregistrationRelated", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<PayrollRepayment_Result> PayrollRepayment(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollRepayment_Result>("PayrollRepayment", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<PayrollRevenueEarned_Result> PayrollRevenueEarned(Nullable<System.DateTime> endDate)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollRevenueEarned_Result>("PayrollRevenueEarned", endDateParameter);
        }
    
        public virtual ObjectResult<PayrollRevenueReceived_Result> PayrollRevenueReceived(Nullable<System.DateTime> endDate)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollRevenueReceived_Result>("PayrollRevenueReceived", endDateParameter);
        }
    
        public virtual ObjectResult<PayrollUserRelated_Result> PayrollUserRelated(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PayrollUserRelated_Result>("PayrollUserRelated", startDateParameter, endDateParameter);
        }
    
        public virtual int ReferralAgentPerformance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ReferralAgentPerformance");
        }
    
        public virtual ObjectResult<Repayment_Result> Repayment(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Repayment_Result>("Repayment", startDateParameter, endDateParameter);
        }
    
        public virtual int RevenueReceived(Nullable<System.DateTime> endDate)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RevenueReceived", endDateParameter);
        }
    
        public virtual int UpdatePartner(Nullable<double> myTimer, string myTokenVal, string partnerID, Nullable<int> recID)
        {
            var myTimerParameter = myTimer.HasValue ?
                new ObjectParameter("myTimer", myTimer) :
                new ObjectParameter("myTimer", typeof(double));
    
            var myTokenValParameter = myTokenVal != null ?
                new ObjectParameter("myTokenVal", myTokenVal) :
                new ObjectParameter("myTokenVal", typeof(string));
    
            var partnerIDParameter = partnerID != null ?
                new ObjectParameter("partnerID", partnerID) :
                new ObjectParameter("partnerID", typeof(string));
    
            var recIDParameter = recID.HasValue ?
                new ObjectParameter("RecID", recID) :
                new ObjectParameter("RecID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePartner", myTimerParameter, myTokenValParameter, partnerIDParameter, recIDParameter);
        }
    }
}
